run:
	sudo docker run -p 8888:8888 --mount type=bind,source=/home/vmihaylov/ML/anomaly_detection_with_python/2_analyzing_and_visualizing_the_anomalous_dataset/liveProject/jupyter,target=/src mikhailov.tech/2_analysing_and_visualizing_the_anomalous_dataset
