run:
	sudo docker run -p 8888:8888 --mount type=bind,source=/home/vmihaylov/ML/anomaly_detection_with_python/3_training_an_anomaly_detection_model/liveProject/jupyter,target=/src mikhailov.tech/3_training_an_anomaly_detection_model
build:
	sudo docker build -t mikhailov.tech/3_training_an_anomaly_detection_model .
