run:
	sudo docker run -p 8888:8888 mikhailov.tech/6_integrating_the_metrics_collection_functionality_in_the_web_service
build:
	sudo docker build -t mikhailov.tech/6_integrating_the_metrics_collection_functionality_in_the_web_service .
